name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain:
          - stable
          - beta
          - nightly 

    steps:
    - uses: actions/checkout@v3
    - run: rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }}
    - name: Build
      run: cargo build --manifest-path=/home/runner/work/SE-PRE-Scheme/api/cargo.toml --verbose
    - name: Run tests
      run: cargo test --manifest-path=/home/runner/work/SE-PRE-Scheme/api/cargo.toml --verbose
